version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      github:
        patterns:
          - "actions/*"
          - "octokit/*"
          - "github/*"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    groups:
       dependencies:
          patterns:
            - "octokit/*"
            - "https-proxy-agent"
       dev-dependencies:
          patterns:
            - "@types/*"
            - "@vercel/*"
            - "eslint*"
            - "jest/*"
            - "typescript"
            - "*"
    schedule:
      interval: "weekly"
