name: 'forker'
author: 'lelia'
branding:
  icon: 'git-branch'
  color: 'green'
description: 'Github action for automating fork creation'
inputs:
  token:
    description: 'Github API token'
    required: true
    default: ${{ github.token }}
  owner:
    description: 'Owner of Github repository being forked'
    required: true
  repo:
    description: 'Github repository being forked'
    required: true
  org:
    description: 'Github organization to fork the repository into'
    required: false
  user:
    description: 'Github user requesting the fork'
    required: false
  addUser:
    description: 'Add Github user to organization if missing'
    required: false
    default: false
  licenseAllowlist:
    description: 'List of allowed licenses for repository being forked'
    required: false
    default: 'undefined'
runs:
  using: 'node12'
  main: 'dist/index.js'
