name: build

on: # Rebuild any PRs and main branch changes
  push:
    branches:
      - main
  # pull_request_target:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      INPUT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: "🛠 run npm build"
      # uses: ./
      with:
        ref: ${{ github.event.pull_request.head.sha }}
      run: |
        npm install
        npm run all
      # with:
      #   ref: ${{ github.event.pull_request.head.sha }}
      #   name: "🛠 run npm build"
      #   run: |
      #     npm install
      # - run: |
      #     npm run all
