name: build

on: # Rebuild any PRs and main branch changes
  push:
    branches:
      - main
  pull_request_target:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      INPUT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: "🛠 run npm build"
      uses: ./
      with:
        path: ./
        ref: ${{ github.event.pull_request.head.sha }}
      run: |
        npm install
        npm run all
