name: build

on: # Rebuild any PRs and main branch changes
  push:
    branches:
      - main
  pull_request_target:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      INPUT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        name: "🛠 test npm build"
      - run: |
          npm install
      - run: |
          npm run all
