name: build

on: # Rebuild any PRs and main branch changes
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      INPUT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: "🛠 run npm build"
      uses: actions/checkout@v2
      run: |
        npm install
        npm run all
