name: build-fork

on: # Rebuild any PRs submitted by forks
  pull_request:

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ⬇️ lint markdown files
        uses: avto-dev/markdown-lint@v1
        with:
          config: '.markdownlint.json'
          args: '**/*.md .github/**/*.md'
  build-fork:
    if: ${{ github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    env:
      INPUT_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      INPUT_OWNER: tremor-rs
      INPUT_REPO: tremor-runtime
      INPUT_USER: lhasa-ospo
      INPUT_CHECKUSER: false
      INPUT_PROMOTEUSER: false
      INPUT_LICENSEALLOWLIST: "0bsd\napache-2.0\nbsd-2-clause\nbsd-3-clause\nmit"
    steps:
      - uses: actions/checkout@v4
      - name: "🛠 build + test npm"
        run: npm run fork
