name: Tests

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      owner:
        description: 'Owner of Github repository being forked'
        required: true
      repo:
        description: 'Github repository being forked'
        required: true
      org:
        description: 'Github organization to fork the repository into'
        required: false
      user:
        description: 'Github user requesting the fork'
        required: false
      addUser:
        description: 'Add Github user to organization if missing'
        required: false
        default: false
      licenseWhitelist:
        description: 'List of allowed licenses for repository being forked'
        required: false
        default: 'undefined'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action can fork into organizations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        name: "🚀 test github user workflow"
        with:
          path: ./
          token: ${{ secrets.GH_API_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha }}
          repo: tremor-runtime
          owner: tremor-rs
          user: lelia
      - uses: ./
        name: "🌎 test github org workflow"
        with:
          path: ./
          token: ${{ secrets.GH_API_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha }}
          licenseWhitelist: "0bsd\napache-2.0\nmit"
          repo: backstage-plugin-buildkite
          owner: RoadieHQ
          org: wayfair-contribs
          user: lelia
          addUser: true
