name: tests
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      # - "releases/*"

jobs:

  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all

  test: # make sure the action can fork to personal namespaces
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          path: ./
          token: ${{ secrets.GH_API_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha }}
          repo: tremor-runtime
          owner: tremor-rs
          user: lelia

  integration: # make sure the action can fork into organizations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          path: ./
          token: ${{ secrets.GH_API_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha }}
          licenseWhitelist: "0bsd\napache-2.0\nmit"
          repo: tremor-runtime
          owner: tremor-rs
          org: wayfair-contribs
          user: lelia
          addUser: true
