name: tests

on: # Rebuild any PRs and main branch changes
  push:
    branches:
      - main
  pull_request_target:
    if: ${{ github.event.pull_request.head.repo.full_name == 'wayfair-incubator/forker' }}
  pull_request:
    if: ${{ github.event.pull_request.head.repo.full_name != 'wayfair-incubator/forker' }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      INPUT_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      INPUT_OWNER: tremor-rs
      INPUT_REPO: tremor-runtime
      INPUT_USER: lhasa-ospo
      INPUT_CHECKUSER: false
      INPUT_PROMOTEUSER: false
      INPUT_LICENSEALLOWLIST: "0bsd\napache-2.0\nbsd-2-clause\nbsd-3-clause\nmit"
    steps:
      - uses: actions/checkout@v3
        name: "🛠 run npm build"
      - run: npm run all
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "🚀 test github user workflow"
        uses: ./
        with:
          path: ./
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha }}
          repo: tremor-runtime
          owner: tremor-rs
          user: lhasa-ospo
      - name: "🌎 test github org workflow"
        uses: ./
        with:
          path: ./
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha }}
          licenseAllowlist: "0bsd\napache-2.0\nbsd-2-clause\nbsd-3-clause\nmit"
          repo: roadie-backstage-plugins
          owner: RoadieHQ
          org: wayfair-contribs
          user: lhasa-ospo
          checkUser: true
          promoteUser: true
