name: Tests

on: # Rebuild any PRs and main branch changes

  pull_request:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      INPUT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        name: "🛠 test npm build"
      - run: |
          npm install
      - run: |
          npm run all

##############################################################################
# Integration tests temporarily disabled while token access issue is diagnosed
##############################################################################

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        name: "🚀 test github user workflow"
        with:
          path: ./
          token: ${{ secrets.GH_API_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha }}
          repo: tremor-runtime
          owner: tremor-rs
          user: lelia
      - uses: ./
        name: "🌎 test github org workflow"
        with:
          path: ./
          token: ${{ secrets.GH_API_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha }}
          licenseAllowlist: "0bsd\napache-2.0\nmit"
          repo: roadie-backstage-plugins
          owner: RoadieHQ
          org: wayfair-contribs
          user: lelia
          addUser: true
