name: Tests

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   env:
  #     INPUT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: |
  #         npm install
  #     - run: |
  #         npm run all
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        name: "🚀 test github user workflow"
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          # ref: ${{ github.event.pull_request.head.sha }}
          repo: tremor-runtime
          owner: tremor-rs
          user: lelia
          # path: ./
      # - uses: ./
      #   name: "🌎 test github org workflow"
      #   env:
      #     INPUT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     token: ${{ secrets.ACCESS_TOKEN }}
      #     ref: ${{ github.event.pull_request.head.sha }}
      #     licenseAllowlist: "0bsd\napache-2.0\nmit"
      #     repo: roadie-backstage-plugins
      #     owner: RoadieHQ
      #     org: wayfair-contribs
      #     user: lelia
      #     addUser: true
      #     path: ./
